imports:
    - { resource: '@SyliusAdminOrderCreationPlugin/Resources/config/services.xml' }

sylius_grid:
    grids:
        sylius_admin_order:
            actions:
                main:
                    create:
                        type: default
                        label: sylius.ui.create
                        icon: plus
                        options:
                            link:
                                route: sylius_admin_order_creation_select_order_customer
                                parameters: []

sylius_mailer:
    emails:
        order_created_in_admin_panel:
            subject: 'sylius_admin_order_creation.email.order_created.subject'
            template: 'SyliusAdminOrderCreationPlugin:Emails:orderCreated.html.twig'

sylius_order:
    resources:
        order:
            classes:
                model: Sylius\AdminOrderCreationPlugin\Entity\Order
        order_item:
            classes:
                model: Sylius\AdminOrderCreationPlugin\Entity\OrderItem
