sylius_admin_order_creation_select_order_customer:
    path: /admin/orders/new/select-customer
    methods: [GET]
    defaults:
        _controller: Sylius\AdminOrderCreationPlugin\Controller\SelectNewOrderCustomerAction

sylius_admin_order_creation_order_preview:
    path: /admin/orders/new/{customerEmail}/preview
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.order:previewAction
        _sylius:
            form:
                type: Sylius\AdminOrderCreationPlugin\Form\Type\NewOrderType
            factory:
                method: createForCustomer
                arguments: [$customerEmail]

sylius_admin_order_creation_order_create:
    path: /admin/orders/new/{customerEmail}
    methods: [GET, POST]
    options:
        expose: true
    defaults:
        _controller: sylius.controller.order:createAction
        _sylius:
            event: admin_create
            section: admin
            permission: true
            template: SyliusAdminOrderCreationPlugin::orderCreate.html.twig
            form:
                type: Sylius\AdminOrderCreationPlugin\Form\Type\NewOrderType
            factory:
                method: createForCustomer
                arguments: [$customerEmail]

sylius_admin_order_creation_reorder:
    path: /admin/orders/{id}/reorder
    methods: [GET, POST]
    options:
        expose: true
    defaults:
        _controller: sylius.controller.order:createAction
        _sylius:
            event: admin_create
            section: admin
            permission: true
            template: SyliusAdminOrderCreationPlugin::orderCreate.html.twig
            form:
                type: Sylius\AdminOrderCreationPlugin\Form\Type\NewOrderType
            factory:
                method: createFromExistingOrder
                arguments: ["expr:service('sylius.repository.order').find($id)"]

sylius_admin_order_creation_ajax:
    prefix: /ajax
    resource: "@SyliusAdminOrderCreationPlugin/Resources/config/app/ajax.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
