sylius_admin_order_creation_select_order_customer:
    path: /admin/orders/new/select-customer
    methods: [GET]
    defaults:
        _controller: Sylius\AdminOrderCreationPlugin\Controller\SelectNewOrderCustomerAction

sylius_admin_order_creation_order_create:
    path: /admin/orders/new/{customerEmail}
    methods: [GET, POST]
    options:
        expose: true
    defaults:
        _controller: sylius.controller.order:createAction
        _sylius:
            event: admin_create
            section: admin
            permission: true
            template: SyliusAdminOrderCreationPlugin::orderCreate.html.twig
            form:
                type: Sylius\AdminOrderCreationPlugin\Form\Type\NewOrderType
            factory:
                method: createForCustomer
                arguments: [$customerEmail]

sylius_admin_order_creation_ajax_customer:
    path: /customer-search
    methods: [GET]
    defaults:
        _controller: sylius.controller.customer:indexAction
        _format: json
        _sylius:
            permission: true
            repository:
                method: findByEmailPart
                arguments: $email

sylius_admin_order_creation_ajax_customer_by_email:
    path: /customer-serach-by-code
    methods: [GET]
    defaults:
        _controller: sylius.controller.customer:indexAction
        _format: json
        _sylius:
            permission: true
            repository:
                method: findBy
                arguments: [email: $email]

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
